# Generated by Django 4.0.4 on 2022-06-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registeraccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
